// Generated by tools/generate-enterprise-wire.py; edit the Core schema, then regenerate.
// Source SHA256: d73f96f73e7270e326bf45ece4abad3f7b686704610cc3bff8b47b96811cf3c8
package net.weero.measix.pilot.data.enterprise

import kotlinx.serialization.Serializable

@Serializable
internal data class PlatformDiscovery(
    val product: PlatformDiscoveryProduct,
    val protocolVersion: String,
    val deploymentId: String,
    val deploymentName: String,
    val clientApiBase: String,
    val runtimeApiBase: String,
    val supportedSnapshotSchemaVersions: List<Long>,
) {
    init {
        require(protocolVersion in setOf("1")) { "invalid_platform_Discovery_protocolVersion" }
        require(Regex("^dep_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(deploymentId)) { "invalid_platform_Discovery_deploymentId" }
        require(Regex("^/").containsMatchIn(clientApiBase)) { "invalid_platform_Discovery_clientApiBase" }
        require(Regex("^/").containsMatchIn(runtimeApiBase)) { "invalid_platform_Discovery_runtimeApiBase" }
    }
}

@Serializable
internal enum class PlatformDiscoveryProduct { MEASIX_AGENT_PLATFORM }

@Serializable
internal data class PlatformEnrollmentExchangeRequest(
    val code: String,
    val installationId: String,
    val deviceName: String,
    val appVersion: String,
    val platform: PlatformEnrollmentExchangeRequestPlatform,
) {
    init {
        require(Regex("^ins_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(installationId)) { "invalid_platform_EnrollmentExchangeRequest_installationId" }
    }
    override fun toString(): String = "PlatformEnrollmentExchangeRequest(redacted)"
}

@Serializable
internal enum class PlatformEnrollmentExchangeRequestPlatform { ANDROID }

@Serializable
internal data class PlatformEnrollmentExchangeResponse(
    val deploymentId: String,
    val userId: String,
    val deviceId: String,
    val sessionId: String,
    val accessToken: String,
    val accessTokenExpiresAt: String,
    val refreshToken: String,
    val refreshExpiresAt: String,
    val sessionIdleExpiresAt: String,
) {
    init {
        require(Regex("^dep_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(deploymentId)) { "invalid_platform_EnrollmentExchangeResponse_deploymentId" }
        require(Regex("^usr_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(userId)) { "invalid_platform_EnrollmentExchangeResponse_userId" }
        require(Regex("^dev_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(deviceId)) { "invalid_platform_EnrollmentExchangeResponse_deviceId" }
        require(Regex("^ses_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(sessionId)) { "invalid_platform_EnrollmentExchangeResponse_sessionId" }
        require(platformWireTimestamp(accessTokenExpiresAt)) { "invalid_platform_EnrollmentExchangeResponse_accessTokenExpiresAt" }
        require(platformWireTimestamp(refreshExpiresAt)) { "invalid_platform_EnrollmentExchangeResponse_refreshExpiresAt" }
        require(platformWireTimestamp(sessionIdleExpiresAt)) { "invalid_platform_EnrollmentExchangeResponse_sessionIdleExpiresAt" }
    }
    override fun toString(): String = "PlatformEnrollmentExchangeResponse(redacted)"
}

@Serializable
internal data class PlatformRefreshRequest(
    val refreshToken: String,
) {
    override fun toString(): String = "PlatformRefreshRequest(redacted)"
}

@Serializable
internal data class PlatformRefreshResponse(
    val accessToken: String,
    val accessTokenExpiresAt: String,
    val refreshToken: String,
    val refreshExpiresAt: String,
    val sessionIdleExpiresAt: String,
) {
    init {
        require(platformWireTimestamp(accessTokenExpiresAt)) { "invalid_platform_RefreshResponse_accessTokenExpiresAt" }
        require(platformWireTimestamp(refreshExpiresAt)) { "invalid_platform_RefreshResponse_refreshExpiresAt" }
        require(platformWireTimestamp(sessionIdleExpiresAt)) { "invalid_platform_RefreshResponse_sessionIdleExpiresAt" }
    }
    override fun toString(): String = "PlatformRefreshResponse(redacted)"
}

@Serializable
internal data class PlatformManagedState(
    val runtimeStatus: PlatformManagedStateRuntimeStatus,
    val activeManagedGeneration: Long,
    val managedStateRevision: Long,
    val syncRequired: Boolean,
    val targetManagedGeneration: Long? = null,
    val runtimeBlocked: Boolean,
) {
    init {
        require(activeManagedGeneration >= 0) { "invalid_platform_ManagedState_activeManagedGeneration" }
        require(managedStateRevision >= 0) { "invalid_platform_ManagedState_managedStateRevision" }
        require(targetManagedGeneration?.let { it >= 1 } != false) { "invalid_platform_ManagedState_targetManagedGeneration" }
    }
}

@Serializable
internal enum class PlatformManagedStateRuntimeStatus { READY, ACTIVATING, DEGRADED }

@Serializable
internal data class PlatformBootstrap(
    val deployment: PlatformBootstrapDeployment,
    val user: PlatformBootstrapUser,
    val device: PlatformBootstrapDevice,
    val session: PlatformBootstrapSession,
    val supportedSnapshotSchemaVersions: List<Long>,
    val managedState: PlatformManagedState,
)

@Serializable
internal data class PlatformBootstrapDeployment(
    val deploymentId: String,
    val name: String,
) {
    init {
        require(Regex("^dep_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(deploymentId)) { "invalid_platform_BootstrapDeployment_deploymentId" }
    }
}

@Serializable
internal data class PlatformBootstrapUser(
    val userId: String,
    val displayName: String,
) {
    init {
        require(Regex("^usr_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(userId)) { "invalid_platform_BootstrapUser_userId" }
    }
}

@Serializable
internal data class PlatformBootstrapDevice(
    val deviceId: String,
    val status: PlatformBootstrapDeviceStatus,
) {
    init {
        require(Regex("^dev_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(deviceId)) { "invalid_platform_BootstrapDevice_deviceId" }
    }
}

@Serializable
internal enum class PlatformBootstrapDeviceStatus { ACTIVE, REVOKED }

@Serializable
internal data class PlatformBootstrapSession(
    val sessionId: String,
    val expiresAt: String,
    val sessionIdleExpiresAt: String,
) {
    init {
        require(Regex("^ses_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(sessionId)) { "invalid_platform_BootstrapSession_sessionId" }
        require(platformWireTimestamp(expiresAt)) { "invalid_platform_BootstrapSession_expiresAt" }
        require(platformWireTimestamp(sessionIdleExpiresAt)) { "invalid_platform_BootstrapSession_sessionIdleExpiresAt" }
    }
}

@Serializable
internal data class PlatformManagedSnapshot(
    val deploymentId: String,
    val schemaVersion: Long,
    val managedGeneration: Long,
    val releaseId: String,
    val snapshotHash: String,
    val providers: List<PlatformProviderDefinition>,
    val models: List<PlatformModelDefinition>,
    val imageGenerators: List<PlatformImageGenerationDefinition>? = null,
    val tts: List<PlatformTtsDefinition>,
    val asr: List<PlatformAsrDefinition>,
    val mcp: List<PlatformMcpDefinition>,
    val policy: PlatformManagedPolicy,
    val metadata: PlatformManagedSnapshotMetadata,
    val assistants: List<PlatformManagedAssistantDefinition>,
    val starters: List<PlatformAssistantStarterDefinition>,
) {
    init {
        require(Regex("^dep_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(deploymentId)) { "invalid_platform_ManagedSnapshot_deploymentId" }
        require(schemaVersion in setOf(4L)) { "invalid_platform_ManagedSnapshot_schemaVersion" }
        require(managedGeneration >= 1) { "invalid_platform_ManagedSnapshot_managedGeneration" }
        require(Regex("^rel_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(releaseId)) { "invalid_platform_ManagedSnapshot_releaseId" }
        require(Regex("^sha256:[0-9a-f]{64}\$").containsMatchIn(snapshotHash)) { "invalid_platform_ManagedSnapshot_snapshotHash" }
    }
}

@Serializable
internal data class PlatformProviderDefinition(
    val providerId: String,
    val displayName: String,
    val clientProtocol: PlatformProviderDefinitionClientProtocol,
    val enabled: Boolean,
) {
    init {
        require(Regex("^prv_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(providerId)) { "invalid_platform_ProviderDefinition_providerId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_ProviderDefinition_displayName" }
    }
}

@Serializable
internal enum class PlatformProviderDefinitionClientProtocol { OPENAI_CHAT_COMPLETIONS, OPENAI_RESPONSES, GOOGLE_GENERATE_CONTENT, ANTHROPIC_MESSAGES }

@Serializable
internal data class PlatformModelDefinition(
    val modelId: String,
    val providerId: String,
    val displayName: String,
    val upstreamModelKey: String,
    val runtimePath: String,
    val inputModalities: List<PlatformModelDefinitionInputModalitiesItem>,
    val outputModalities: List<PlatformModelDefinitionOutputModalitiesItem>,
    val capabilities: List<PlatformModelDefinitionCapabilitiesItem>,
    val enabled: Boolean,
) {
    init {
        require(Regex("^mdl_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(modelId)) { "invalid_platform_ModelDefinition_modelId" }
        require(Regex("^prv_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(providerId)) { "invalid_platform_ModelDefinition_providerId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_ModelDefinition_displayName" }
        require(upstreamModelKey.codePointCount(0, upstreamModelKey.length) >= 1) { "invalid_platform_ModelDefinition_upstreamModelKey" }
        require(Regex("^/[^?#]*\$").containsMatchIn(runtimePath)) { "invalid_platform_ModelDefinition_runtimePath" }
        require(inputModalities.size >= 1) { "invalid_platform_ModelDefinition_inputModalities" }
        require(outputModalities.size >= 1) { "invalid_platform_ModelDefinition_outputModalities" }
    }
}

@Serializable
internal enum class PlatformModelDefinitionInputModalitiesItem { TEXT, IMAGE }

@Serializable
internal enum class PlatformModelDefinitionOutputModalitiesItem { TEXT }

@Serializable
internal enum class PlatformModelDefinitionCapabilitiesItem { TOOL, REASONING }

@Serializable
internal data class PlatformImageGenerationDefinition(
    val imageId: String,
    val displayName: String,
    val clientProtocol: PlatformImageGenerationDefinitionClientProtocol,
    val upstreamModelKey: String,
    val runtimePath: String,
    val maxImagesPerRequest: Long,
    val allowedSizes: List<String>,
    val enabled: Boolean,
) {
    init {
        require(Regex("^img_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(imageId)) { "invalid_platform_ImageGenerationDefinition_imageId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_ImageGenerationDefinition_displayName" }
        require(upstreamModelKey.codePointCount(0, upstreamModelKey.length) >= 1) { "invalid_platform_ImageGenerationDefinition_upstreamModelKey" }
        require(Regex("^/[^?#]*\$").containsMatchIn(runtimePath)) { "invalid_platform_ImageGenerationDefinition_runtimePath" }
        require(maxImagesPerRequest >= 1 && maxImagesPerRequest <= 6) { "invalid_platform_ImageGenerationDefinition_maxImagesPerRequest" }
        require(allowedSizes.size >= 1 && allowedSizes.distinct().size == allowedSizes.size) { "invalid_platform_ImageGenerationDefinition_allowedSizes" }
        allowedSizes.forEach { item ->
            require(Regex("^(auto|[1-9][0-9]*x[1-9][0-9]*)\$").containsMatchIn(item)) { "invalid_platform_ImageGenerationDefinition_allowedSizes_item" }
        }
    }
}

@Serializable
internal enum class PlatformImageGenerationDefinitionClientProtocol { OPENAI_IMAGES_GENERATIONS }

@Serializable
internal data class PlatformTtsDefinition(
    val ttsId: String,
    val displayName: String,
    val clientProtocol: PlatformTtsDefinitionClientProtocol,
    val upstreamModelKey: String? = null,
    val voice: String? = null,
    val runtimePath: String? = null,
    val voiceDesignPrompt: String? = null,
    val speechRate: Double? = null,
    val pitch: Double? = null,
    val enabled: Boolean,
) {
    init {
        require(Regex("^tts_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(ttsId)) { "invalid_platform_TtsDefinition_ttsId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_TtsDefinition_displayName" }
        require(upstreamModelKey?.let { it.codePointCount(0, it.length) >= 1 } != false) { "invalid_platform_TtsDefinition_upstreamModelKey" }
        require(voice?.let { it.codePointCount(0, it.length) >= 1 } != false) { "invalid_platform_TtsDefinition_voice" }
        require(runtimePath?.let { Regex("^/[^?#]*\$").containsMatchIn(it) } != false) { "invalid_platform_TtsDefinition_runtimePath" }
        require(voiceDesignPrompt?.let { it.codePointCount(0, it.length) >= 1 } != false) { "invalid_platform_TtsDefinition_voiceDesignPrompt" }
        require(speechRate?.let { it > 0 && it.isFinite() } != false) { "invalid_platform_TtsDefinition_speechRate" }
        require(pitch?.let { it > 0 && it.isFinite() } != false) { "invalid_platform_TtsDefinition_pitch" }
    }
}

@Serializable
internal enum class PlatformTtsDefinitionClientProtocol { OPENAI_AUDIO_SPEECH, GEMINI_GENERATE_CONTENT_TTS, MIMO_CHAT_COMPLETIONS_TTS, SYSTEM_TTS }

@Serializable
internal data class PlatformAsrDefinition(
    val asrId: String,
    val displayName: String,
    val clientProtocol: PlatformAsrDefinitionClientProtocol,
    val upstreamModelKey: String,
    val language: String? = null,
    val sampleRate: Long? = null,
    val vadThreshold: Double? = null,
    val silenceDurationMs: Long? = null,
    val prefixPaddingMs: Long? = null,
    val prompt: String? = null,
    val runtimePath: String,
    val enabled: Boolean,
) {
    init {
        require(Regex("^asr_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(asrId)) { "invalid_platform_AsrDefinition_asrId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_AsrDefinition_displayName" }
        require(upstreamModelKey.codePointCount(0, upstreamModelKey.length) >= 1) { "invalid_platform_AsrDefinition_upstreamModelKey" }
        require(language?.let { it.codePointCount(0, it.length) >= 1 } != false) { "invalid_platform_AsrDefinition_language" }
        require(sampleRate?.let { it in setOf(8000L, 16000L, 24000L) } != false) { "invalid_platform_AsrDefinition_sampleRate" }
        require(vadThreshold?.let { it >= 0 && it <= 1 && it.isFinite() } != false) { "invalid_platform_AsrDefinition_vadThreshold" }
        require(silenceDurationMs?.let { it >= 1 } != false) { "invalid_platform_AsrDefinition_silenceDurationMs" }
        require(prefixPaddingMs?.let { it >= 0 } != false) { "invalid_platform_AsrDefinition_prefixPaddingMs" }
        require(prompt?.let { it.codePointCount(0, it.length) >= 1 } != false) { "invalid_platform_AsrDefinition_prompt" }
        require(Regex("^/[^?#]*\$").containsMatchIn(runtimePath)) { "invalid_platform_AsrDefinition_runtimePath" }
    }
}

@Serializable
internal enum class PlatformAsrDefinitionClientProtocol { OPENAI_AUDIO_TRANSCRIPTIONS, DASHSCOPE_HTTP_ASR, OPENAI_REALTIME_TRANSCRIPTION, DASHSCOPE_REALTIME_ASR }

@Serializable
internal data class PlatformMcpDefinition(
    val mcpServerId: String,
    val displayName: String,
    val clientProtocol: PlatformMcpDefinitionClientProtocol,
    val runtimePath: String,
    val authOwnership: PlatformMcpDefinitionAuthOwnership,
    val enabled: Boolean,
) {
    init {
        require(Regex("^mcp_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(mcpServerId)) { "invalid_platform_McpDefinition_mcpServerId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_McpDefinition_displayName" }
        require(Regex("^/[^?#]*\$").containsMatchIn(runtimePath)) { "invalid_platform_McpDefinition_runtimePath" }
    }
}

@Serializable
internal enum class PlatformMcpDefinitionClientProtocol { MCP_STREAMABLE_HTTP }

@Serializable
internal enum class PlatformMcpDefinitionAuthOwnership { ENTERPRISE_MANAGED, NONE }

@Serializable
internal data class PlatformManagedPolicy(
    val policyId: String,
    val allowLocalProviders: Boolean,
    val allowLocalTts: Boolean,
    val allowLocalAsr: Boolean,
    val allowLocalMcp: Boolean,
    val allowLocalAssistants: Boolean,
    val defaultModelId: String? = null,
    val defaultImageGenerationId: String? = null,
    val defaultTtsId: String? = null,
    val defaultAsrId: String? = null,
    val defaultAssistantId: String? = null,
) {
    init {
        require(Regex("^pol_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(policyId)) { "invalid_platform_ManagedPolicy_policyId" }
        require(defaultModelId?.let { Regex("^mdl_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_ManagedPolicy_defaultModelId" }
        require(defaultImageGenerationId?.let { Regex("^img_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_ManagedPolicy_defaultImageGenerationId" }
        require(defaultTtsId?.let { Regex("^tts_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_ManagedPolicy_defaultTtsId" }
        require(defaultAsrId?.let { Regex("^asr_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_ManagedPolicy_defaultAsrId" }
        require(defaultAssistantId?.let { Regex("^asd_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_ManagedPolicy_defaultAssistantId" }
    }
}

@Serializable
internal data class PlatformManagedSnapshotMetadata(
    val publishedAt: String,
    val publishedByUserId: String? = null,
) {
    init {
        require(platformWireTimestamp(publishedAt)) { "invalid_platform_ManagedSnapshotMetadata_publishedAt" }
        require(publishedByUserId?.let { Regex("^usr_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_ManagedSnapshotMetadata_publishedByUserId" }
    }
}

@Serializable
internal data class PlatformManagedAssistantDefinition(
    val assistantDefinitionId: String,
    val displayName: String,
    val description: String? = null,
    val systemPrompt: String,
    val modelId: String,
    val memorySeed: List<String>,
    val mcpServerIds: List<String>,
    val enabled: Boolean,
) {
    init {
        require(Regex("^asd_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(assistantDefinitionId)) { "invalid_platform_ManagedAssistantDefinition_assistantDefinitionId" }
        require(displayName.codePointCount(0, displayName.length) >= 1) { "invalid_platform_ManagedAssistantDefinition_displayName" }
        require(systemPrompt.codePointCount(0, systemPrompt.length) >= 1) { "invalid_platform_ManagedAssistantDefinition_systemPrompt" }
        require(Regex("^mdl_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(modelId)) { "invalid_platform_ManagedAssistantDefinition_modelId" }
        memorySeed.forEach { item ->
            require(item.codePointCount(0, item.length) >= 1) { "invalid_platform_ManagedAssistantDefinition_memorySeed_item" }
        }
        mcpServerIds.forEach { item ->
            require(Regex("^mcp_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(item)) { "invalid_platform_ManagedAssistantDefinition_mcpServerIds_item" }
        }
    }
}

@Serializable
internal data class PlatformAssistantStarterDefinition(
    val starterId: String,
    val assistantDefinitionId: String,
    val title: String,
    val prompt: String,
    val description: String? = null,
    val sortOrder: Long,
    val enabled: Boolean,
) {
    init {
        require(Regex("^str_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(starterId)) { "invalid_platform_AssistantStarterDefinition_starterId" }
        require(Regex("^asd_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(assistantDefinitionId)) { "invalid_platform_AssistantStarterDefinition_assistantDefinitionId" }
        require(title.codePointCount(0, title.length) >= 1) { "invalid_platform_AssistantStarterDefinition_title" }
        require(prompt.codePointCount(0, prompt.length) >= 1) { "invalid_platform_AssistantStarterDefinition_prompt" }
        require(sortOrder >= 0) { "invalid_platform_AssistantStarterDefinition_sortOrder" }
    }
}

@Serializable
internal data class PlatformManagedAppliedReport(
    val managedGeneration: Long,
    val snapshotHash: String,
) {
    init {
        require(managedGeneration >= 1) { "invalid_platform_ManagedAppliedReport_managedGeneration" }
        require(snapshotHash.codePointCount(0, snapshotHash.length) >= 1) { "invalid_platform_ManagedAppliedReport_snapshotHash" }
    }
}

@Serializable
internal data class PlatformPortalGrant(
    val exchangeUrl: String,
    val ticket: String,
    val expiresAt: String,
) {
    init {
        require(platformWireTimestamp(expiresAt)) { "invalid_platform_PortalGrant_expiresAt" }
    }
    override fun toString(): String = "PlatformPortalGrant(redacted)"
}

@Serializable
internal data class PlatformUserBudgetView(
    val userId: String,
    val timezone: String,
    val items: List<PlatformBudgetCapabilityView>,
    val asOf: String,
) {
    init {
        require(Regex("^usr_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(userId)) { "invalid_platform_UserBudgetView_userId" }
        require(items.size >= 5 && items.size <= 5) { "invalid_platform_UserBudgetView_items" }
        require(platformWireTimestamp(asOf)) { "invalid_platform_UserBudgetView_asOf" }
        require(items.map { it.capability }.toSet() == PlatformBudgetCapability.entries.toSet()) { "invalid_platform_UserBudgetView_items_capabilities" }
    }
}

@Serializable
internal data class PlatformBudgetCapabilityView(
    val capability: PlatformBudgetCapability,
    val mode: PlatformBudgetMode,
    val source: PlatformBudgetSource,
    val revision: Long,
    val effectiveFrom: String,
    val asOf: String,
    val inFlightRequests: Long,
    val limits: List<PlatformBudgetLimitState>,
    val usageMeters: List<PlatformMeterQuantity>,
    val status: PlatformBudgetStatus,
) {
    init {
        require(revision >= 0) { "invalid_platform_BudgetCapabilityView_revision" }
        require(platformWireTimestamp(effectiveFrom)) { "invalid_platform_BudgetCapabilityView_effectiveFrom" }
        require(platformWireTimestamp(asOf)) { "invalid_platform_BudgetCapabilityView_asOf" }
        require(inFlightRequests >= 0) { "invalid_platform_BudgetCapabilityView_inFlightRequests" }
    }
}

@Serializable
internal enum class PlatformBudgetCapability { MODEL, TTS, ASR, MCP, IMAGE_GENERATION }

@Serializable
internal enum class PlatformBudgetMode { UNLIMITED, LIMITED }

@Serializable
internal enum class PlatformBudgetSource { DEFAULT, EXPLICIT }

@Serializable
internal data class PlatformBudgetLimitState(
    val period: PlatformBudgetPeriod,
    val meter: PlatformUsageMeter,
    val limit: String,
    val used: String,
    val reserved: String,
    val remaining: String,
    val overage: String,
    val scopeStart: String,
    val resetAt: String? = null,
) {
    init {
        require(Regex("^(0|[1-9][0-9]*)(\\.[0-9]{1,9})?\$").containsMatchIn(limit)) { "invalid_platform_BudgetLimitState_limit" }
        require(Regex("^(0|[1-9][0-9]*)(\\.[0-9]{1,9})?\$").containsMatchIn(used)) { "invalid_platform_BudgetLimitState_used" }
        require(Regex("^(0|[1-9][0-9]*)(\\.[0-9]{1,9})?\$").containsMatchIn(reserved)) { "invalid_platform_BudgetLimitState_reserved" }
        require(Regex("^(0|[1-9][0-9]*)(\\.[0-9]{1,9})?\$").containsMatchIn(remaining)) { "invalid_platform_BudgetLimitState_remaining" }
        require(Regex("^(0|[1-9][0-9]*)(\\.[0-9]{1,9})?\$").containsMatchIn(overage)) { "invalid_platform_BudgetLimitState_overage" }
        require(platformWireTimestamp(scopeStart)) { "invalid_platform_BudgetLimitState_scopeStart" }
        require(resetAt?.let { platformWireTimestamp(it) } != false) { "invalid_platform_BudgetLimitState_resetAt" }
    }
}

@Serializable
internal enum class PlatformBudgetPeriod { DAY, WEEK, MONTH, LIFETIME }

@Serializable
internal enum class PlatformUsageMeter { REQUESTS, REQUESTED_IMAGES, INPUT_TOKENS, OUTPUT_TOKENS, CACHED_TOKENS, TOTAL_TOKENS, CHARACTERS, AUDIO_SECONDS }

@Serializable
internal data class PlatformMeterQuantity(
    val meter: PlatformUsageMeter,
    val quantity: String,
    val completeness: PlatformUsageCompleteness,
) {
    init {
        require(Regex("^(0|[1-9][0-9]*)(\\.[0-9]{1,9})?\$").containsMatchIn(quantity)) { "invalid_platform_MeterQuantity_quantity" }
    }
}

@Serializable
internal enum class PlatformUsageCompleteness { EXACT, PARTIAL, UNKNOWN }

@Serializable
internal enum class PlatformBudgetStatus { AVAILABLE, EXHAUSTED, PENDING_RECONCILIATION }

@Serializable
internal data class PlatformProblem(
    val type: String,
    val title: String,
    val status: Long,
    val code: String,
    val detail: String? = null,
    val requestId: String? = null,
    val activationId: String? = null,
    val targetManagedGeneration: Long? = null,
    val currentDraftRevision: Long? = null,
    val forwarded: Boolean? = null,
    val budget: PlatformRuntimeBudgetContext? = null,
) {
    init {
        require(status >= 400 && status <= 599) { "invalid_platform_Problem_status" }
        require(requestId?.let { Regex("^req_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_Problem_requestId" }
        require(activationId?.let { Regex("^act_[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\$").containsMatchIn(it) } != false) { "invalid_platform_Problem_activationId" }
        require(targetManagedGeneration?.let { it >= 0 } != false) { "invalid_platform_Problem_targetManagedGeneration" }
        require(currentDraftRevision?.let { it >= 0 } != false) { "invalid_platform_Problem_currentDraftRevision" }
    }
}

@Serializable
internal data class PlatformRuntimeBudgetContext(
    val capability: PlatformBudgetCapability,
    val resourceId: String? = null,
    val mode: PlatformBudgetMode,
    val blockingLimits: List<PlatformRuntimeBudgetLimitState>,
    val resetAt: String? = null,
    val asOf: String,
) {
    init {
        require(resetAt?.let { platformWireTimestamp(it) } != false) { "invalid_platform_RuntimeBudgetContext_resetAt" }
        require(platformWireTimestamp(asOf)) { "invalid_platform_RuntimeBudgetContext_asOf" }
    }
}

@Serializable
internal data class PlatformRuntimeBudgetLimitState(
    val meter: PlatformUsageMeter,
    val period: PlatformBudgetPeriod,
    val limit: Long,
    val used: Long,
    val reserved: Long,
    val resetAt: String? = null,
) {
    init {
        require(limit >= 0) { "invalid_platform_RuntimeBudgetLimitState_limit" }
        require(used >= 0) { "invalid_platform_RuntimeBudgetLimitState_used" }
        require(reserved >= 0) { "invalid_platform_RuntimeBudgetLimitState_reserved" }
        require(resetAt?.let { platformWireTimestamp(it) } != false) { "invalid_platform_RuntimeBudgetLimitState_resetAt" }
    }
}
